name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          version: 0.0.1
      - uses: actions/checkout@v2
      - uses: ./
        id: run3
        with:
          filename: test_changelogs/CHANGELOG.md
          version: 0.0.3
      - name: check version 3
        env:
          OUT3: ${{steps.run3.outputs.body}}
        run: |
          EXPECTED3="\n### Added\n\n* Code in 0.0.3"
          if [[ $OUT3 == $EXPECTED3 ]] 
            then 
              echo "match!"
          else 
              echo "::error ::no match - [${OUT3}]"
              exit 1
          fi

